version: '3'
services:
  sahi_hai:
    container_name: sahi_hai
    build:
    # Dockerfile path
      context: .
      dockerfile: Dockerfile  
    # Mount the local ./app directory to /var/www/html in the container
    volumes:
      - .:/var/www/html 
    # Map port 4000 on the host to port 80 on the container 
    ports:
      - 8000:80